title = "Template 1a"

[base_sql]
sql = '''SELECT COUNT(*)
FROM title as t,
name as n,
cast_info as ci
WHERE
t.id = ci.movie_id
AND n.id = ci.person_id
AND (Xyear)
AND (Xtitle)
'''

# template 1
[[templates]]

  name = "1a"

  [[templates.predicates]]
  type = "sql"
  columns = ["t.kind_id"]
  keys = ["Xtitle"]
  pred_type = "IN"
  dependencies = 0

  sql = '''
  SELECT t.kind_id, count(*)
  FROM title as t
  GROUP BY t.kind_id
  HAVING COUNT(*) > 10000
  ORDER BY count(*) desc
  '''

  sampling_method = "quantile"
  num_quantiles = 2
  min_samples = 1
  max_samples = 3

  [[templates.predicates]]
  type = "sql"
  columns = ["t.production_year"]
  keys = ["Xyear"]
  pred_type = "<"
  dependencies = 0

  sql = '''
  SELECT t.production_year
  FROM title as t
  '''

  sampling_method = "random"
  num_quantiles = 2
  min_samples = 1
  max_samples = 1
