title = "Template 1a"

[base_sql]
sql = '''SELECT COUNT(*)
FROM "synth_2d_gaussian_100K" AS s
WHERE
(Xcol0)
AND (Xcol1)
'''

# template 1
[[templates]]

  name = "1a"

  [[templates.predicates]]
  type = "sql"
  columns = ["s.col0"]
  keys = ["Xcol0"]
  pred_type = ">"
  dependencies = 0

  sql = '''
  SELECT col0
  FROM "synth_2d_gaussian_100K"
  WHERE col0 <= 23.5
  AND col0 >= 20.0
  '''

  sampling_method = "random"
  min_samples = 1
  max_samples = 1

  [[templates.predicates]]
  type = "sql"
  columns = ["s.col1"]
  keys = ["Xcol1"]
  pred_type = ">"
  dependencies = 0

  sql = '''
  SELECT col1
  FROM "synth_2d_gaussian_100K"
  WHERE col1 <= 33.5
  AND col1 >= 30.0
  '''

  sampling_method = "random"
  min_samples = 1
  max_samples = 1
