title = "Template 1a"

[base_sql]
sql = '''SELECT COUNT(*)
FROM "synth_primary" AS p,
"synth_foreign" as f
WHERE p.id = f.tid
AND (Xtid)
'''

# template 1
[[templates]]

  name = "1a"

  [[templates.predicates]]
  type = "sql"
  columns = ["f.tid"]
  keys = ["Xtid"]
  pred_type = "in"
  dependencies = 0

  sql = '''
  SELECT f.tid,COUNT(*)
  FROM "synth_primary" AS p,
  "synth_foreign" AS f
  WHERE p.id = f.tid
  GROUP BY f.tid
  HAVING COUNT(*) > 10
  ORDER BY COUNT(*)
  '''

  sampling_method = "quantile"
  num_quantiles = 2
  min_samples = 10
  max_samples = 50

