title = ""

[base_sql]

sql = '''SELECT COUNT(*)
FROM
title as t,
movie_info_idx as mii,
info_type as it
WHERE
t.id = mii.movie_id
AND it.id = mii.info_type_id
AND (Xtitle)
AND (Xinfo_type)
'''

# template 1
[[templates]]

  [[templates.predicates]]
  [[templates.predicates.multi]]

  type = "sql"
  columns = ["mii.info_type_id"]
  keys = ["Xinfo_type"]
  pred_type = "<"
  dependencies = 0

  sql = '''
  SELECT mii.info_type_id
  FROM movie_info_idx as mii
  '''

  sampling_method = ""
  min_samples = 1
  max_samples = 1


  [[templates.predicates.multi]]

  type = "sql"
  columns = ["mii.info_type_id"]
  keys = ["Xinfo_type"]
  pred_type = "="
  dependencies = 0

  sql = '''
  SELECT mii.info_type_id
  FROM movie_info_idx as mii
  '''

  sampling_method = ""
  min_samples = 1
  max_samples = 1

  [[templates.predicates]]
  [[templates.predicates.multi]]

  type = "sql"
  columns = ["t.id"]
  keys = ["Xtitle"]
  pred_type = "<"
  dependencies = 0

  sql = '''
  SELECT t.id
  FROM title as t
  '''

  sampling_method = ""
  min_samples = 1
  max_samples = 1


  [[templates.predicates.multi]]

  type = "sql"
  columns = ["t.production_year"]
  keys = ["Xtitle"]
  pred_type = "<"
  dependencies = 0

  sql = '''
  SELECT t.production_year
  FROM title as t
  '''

  sampling_method = ""
  min_samples = 1
  max_samples = 1

  [[templates.predicates.multi]]

  type = "sql"
  columns = ["t.kind_id"]
  keys = ["Xtitle"]
  pred_type = "="
  dependencies = 0

  sql = '''
  SELECT t.kind_id
  FROM title as t
  '''

  sampling_method = ""
  min_samples = 1
  max_samples = 1

  [[templates.predicates.multi]]

  type = "sql"
  columns = ["t.kind_id"]
  keys = ["Xtitle"]
  pred_type = "<"
  dependencies = 0

  sql = '''
  SELECT t.kind_id
  FROM title as t
  '''

  sampling_method = ""
  min_samples = 1
  max_samples = 1
