title = ""

[base_sql]

sql = '''SELECT COUNT(*)
FROM
title as t,
movie_link as ml,
link_type as lt
WHERE
t.id = ml.movie_id
AND lt.id = ml.link_type_id
AND (Xmovie_link)
AND (Xtitle)
'''

# template 1
[[templates]]

  [[templates.predicates]]
  [[templates.predicates.multi]]

  type = "sql"
  columns = ["ml.link_type_id"]
  keys = ["Xmovie_link"]
  pred_type = "<"
  dependencies = 0

  sql = '''
  SELECT ml.link_type_id
  FROM movie_link AS ml
  '''

  sampling_method = ""
  min_samples = 1
  max_samples = 1

  [[templates.predicates.multi]]

  type = "sql"
  columns = ["ml.link_type_id"]
  keys = ["Xmovie_link"]
  pred_type = "="
  dependencies = 0

  sql = '''
  SELECT ml.link_type_id
  FROM movie_link AS ml
  '''

  sampling_method = ""
  min_samples = 1
  max_samples = 1


  [[templates.predicates]]
  [[templates.predicates.multi]]

  type = "sql"
  columns = ["t.id"]
  keys = ["Xtitle"]
  pred_type = "<"
  dependencies = 0

  sql = '''
  SELECT t.id
  FROM title as t
  '''

  sampling_method = ""
  min_samples = 1
  max_samples = 1


  [[templates.predicates.multi]]

  type = "sql"
  columns = ["t.production_year"]
  keys = ["Xtitle"]
  pred_type = "<"
  dependencies = 0

  sql = '''
  SELECT t.production_year
  FROM title as t
  '''

  sampling_method = ""
  min_samples = 1
  max_samples = 1

  [[templates.predicates.multi]]

  type = "sql"
  columns = ["t.kind_id"]
  keys = ["Xtitle"]
  pred_type = "="
  dependencies = 0

  sql = '''
  SELECT t.kind_id
  FROM title as t
  '''

  sampling_method = ""
  min_samples = 1
  max_samples = 1

  [[templates.predicates.multi]]

  type = "sql"
  columns = ["t.kind_id"]
  keys = ["Xtitle"]
  pred_type = "<"
  dependencies = 0

  sql = '''
  SELECT t.kind_id
  FROM title as t
  '''

  sampling_method = ""
  min_samples = 1
  max_samples = 1
