title = ""

[base_sql]

sql = '''SELECT COUNT(*)
FROM
title as t,
movie_companies as mc,
company_type as ct
WHERE
t.id = mc.movie_id
AND ct.id = mc.company_type_id
AND (Xcompany_type)
'''

# template 1
[[templates]]

  [[templates.predicates]]
  [[templates.predicates.multi]]

  type = "sql"
  columns = ["mc.company_type_id"]
  keys = ["Xcompany_type"]
  pred_type = "="
  dependencies = 0

  sql = '''
  SELECT mc.company_type_id
  FROM movie_companies as mc
  '''

  sampling_method = ""
  min_samples = 1
  max_samples = 1


  [[templates.predicates.multi]]

  type = "sql"
  columns = ["mc.company_type_id"]
  keys = ["Xcompany_type"]
  pred_type = "<"
  dependencies = 0

  sql = '''
  SELECT mc.company_type_id
  FROM movie_companies as mc
  '''

  sampling_method = ""
  min_samples = 1
  max_samples = 1

