title = ""

[base_sql]

sql = '''SELECT COUNT(*)
FROM
name as n,
aka_name as an,
person_info as pi
WHERE
n.id = pi.person_id
AND n.id = an.person_id
AND (Xinfo)
'''

# template 1
[[templates]]

  [[templates.predicates]]
  [[templates.predicates.multi]]

  type = "sql"
  columns = ["pi.info_type_id"]
  keys = ["Xinfo"]
  pred_type = "<"
  dependencies = 0

  sql = '''
  SELECT pi.info_type_id
  FROM person_info as pi
  '''

  sampling_method = ""
  min_samples = 1
  max_samples = 1

  [[templates.predicates]]
  [[templates.predicates.multi]]

  type = "sql"
  columns = ["pi.info_type_id"]
  keys = ["Xinfo"]
  pred_type = "="
  dependencies = 0

  sql = '''
  SELECT pi.info_type_id
  FROM person_info as pi
  '''

  sampling_method = ""
  min_samples = 1
  max_samples = 1
