title = ""

[base_sql]

sql = '''SELECT COUNT(*)
FROM
title as t,
complete_cast as cc,
comp_cast_type as cct
WHERE
t.id = cc.movie_id
AND cct.id = cc.status_id
AND (Xcct)
'''

# template 1
[[templates]]

  [[templates.predicates]]
  [[templates.predicates.multi]]

  type = "sql"
  columns = ["cct.id"]
  keys = ["Xcct"]
  pred_type = "="
  dependencies = 0

  sql = '''
  SELECT cct.id
  FROM comp_cast_type AS cct
  '''
  sampling_method = ""
  min_samples = 1
  max_samples = 1

  [[templates.predicates]]
  [[templates.predicates.multi]]

  type = "sql"
  columns = ["cct.id"]
  keys = ["Xcct"]
  pred_type = "<"
  dependencies = 0

  sql = '''
  SELECT cct.id
  FROM comp_cast_type AS cct
  '''
  sampling_method = ""
  min_samples = 1
  max_samples = 1

