title = ""

[base_sql]

sql = '''SELECT COUNT(*)
FROM
title as t,
movie_info as mi,
info_type as it
WHERE
t.id = mi.movie_id
AND it.id = mi.info_type_id
AND (Xinfo_type)
'''

# template 1
[[templates]]

  [[templates.predicates]]
  [[templates.predicates.multi]]

  type = "sql"
  columns = ["mi.info_type_id"]
  keys = ["Xinfo_type"]
  pred_type = "<"
  dependencies = 0

  sql = '''
  SELECT mi.info_type_id
  FROM movie_info as mi
  '''

  sampling_method = ""
  min_samples = 1
  max_samples = 1


  [[templates.predicates.multi]]

  type = "sql"
  columns = ["mi.info_type_id"]
  keys = ["Xinfo_type"]
  pred_type = "="
  dependencies = 0

  sql = '''
  SELECT mi.info_type_id
  FROM movie_info as mi
  '''

  sampling_method = ""
  min_samples = 1
  max_samples = 1
