DROP INDEX answer_site_id_question_id_idx;
DROP INDEX answer_creation_date_idx;
DROP INDEX post_link_site_id_post_id_to_idx;
DROP INDEX question_site_id_id_idx;
DROP INDEX question_creation_date_idx;
DROP INDEX so_user_creation_date_idx;
DROP INDEX so_user_last_access_date_idx;
