title = "Template 1a"

[base_sql]
sql = '''SELECT COUNT(*)
FROM "synth_primary" AS p,
"synth_foreign" as f
WHERE p.id = f.tid
AND (Xtid)
'''

# template 1
[[templates]]

  name = "1a"

  [[templates.predicates]]
  type = "sql"
  columns = ["f.tid"]
  keys = ["Xtid"]
  pred_type = "<"
  dependencies = 0

  sql = '''
  SELECT p.id
  FROM "synth_primary" AS p
  '''

  sampling_method = "random"
  min_samples = 1
  max_samples = 1

