title = "Template 1a"

[base_sql]
sql = '''SELECT COUNT(*)
FROM synth_mix_gaussian AS s
WHERE
(Xcol0)
'''

# template 1
[[templates]]

  name = "1a"

  [[templates.predicates]]
  type = "sql"
  columns = ["s.col0"]
  keys = ["Xcol0"]
  pred_type = "IN"
  dependencies = 0

  sql = '''
  SELECT col0, COUNT(*)
  FROM synth_mix_gaussian
  GROUP BY col0
  HAVING col0 <= 500
  ORDER BY COUNT(*)
  '''

  sampling_method = "quantile"
  num_quantiles = 3
  min_samples = 1
  max_samples = 3
