title = "Template 1a"

[base_sql]
sql = '''SELECT COUNT(*)
FROM synth_columns_gaussian AS s
WHERE
(Xcol1)
'''

# template 1
[[templates]]

  name = "1a"

  [[templates.predicates]]
  type = "sql"
  columns = ["s.col1"]
  keys = ["Xcol1"]
  pred_type = "IN"
  dependencies = 0

  sql = '''
  SELECT DISTINCT col1
  FROM synth_columns_gaussian
  '''

  sampling_method = "random"
  min_samples = 1
  max_samples = 3
