title = "Template 1a"

[base_sql]
sql = '''SELECT COUNT(*)
FROM synth_multi_gaussian4 AS s
WHERE
(Xcol0)
AND (Xcol1)
AND (Xcol2)
'''

# template 1
[[templates]]

  name = "1a"

  [[templates.predicates]]
  type = "sql"
  columns = ["s.col0", "s.col1"]
  keys = ["Xcol0", "Xcol1"]
  pred_type = "IN"
  dependencies = 0

  sql = '''
  SELECT col0,col1,COUNT(*)
  FROM synth_multi_gaussian4
  GROUP BY col0,col1
  ORDER BY COUNT(*)
  '''

  sampling_method = "quantile"
  num_quantiles = 3
  min_samples = 1
  max_samples = 3

  [[templates.predicates]]
  type = "sql"
  columns = ["s.col2"]
  keys = ["Xcol2"]
  pred_type = "IN"
  dependencies = 0

  sql = '''
  SELECT col2
  FROM synth_multi_gaussian4
  GROUP BY col2
  ORDER BY COUNT(*)
  '''

  sampling_method = "quantile"
  num_quantiles = 2
  min_samples = 2
  max_samples = 10
